/** Declaration file generated by dts-gen */

declare module 'find-webpack'{
    
    export function cleanForCypress(opts: any, webpackOptions: any): any;
    
    export function getWebpackOptions(): any;
    
    export function tryLoadingWebpackConfig(webpackConfigPath: any): any;

}    
